version: '3'
services:
    nginx:
        image: 'nginx:latest'
        ports:
            - '80:80'
            - '${SSL_PORT:-443}:443'
        environment:
            - 'SSL_PORT=${SSL_PORT:-443}'
            - APP_SERVICE=laravel.test
            - 'SERVER_NAME=${SERVER_NAME:-localhost}'
        volumes:
            - 'sail-nginx:/etc/nginx/certs'
            - './nginx/templates:/etc/nginx/templates'
            - './vendor/ryoluo/sail-ssl/nginx/generate-ssl-cert.sh:/docker-entrypoint.d/99-generate-ssl-cert.sh'
            - './nginx/logs:/var/log/nginx/'
            - './nginx/config:/etc/nginx/conf.d/'
        networks:
            - sail
    laravel.test:
        mem_limit: 500M
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app:latest_with_newrelic
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '81:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            TZ: America/Sao_Paulo
        volumes:
            - '.:/var/www/html/'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    laravel.test2:
        mem_limit: 500M
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app:latest_with_newrelic
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '82:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            TZ: America/Sao_Paulo
        volumes:
            - '.:/var/www/html/'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - /mnt/wsl/docker-desktop-bind-mounts/:/mnt/wsl/docker-desktop-bind-mounts/
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "25676:25676"
            - "15672:15672"
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-nginx:
        driver: local
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
